name: emarket_delivery_boy
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^7.7.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  dio: ^5.4.3+1
  google_maps_flutter: ^2.6.1
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  url_launcher: ^6.2.6
  firebase_core: ^2.30.1
  firebase_messaging: ^14.9.0
  flutter_local_notifications: ^17.2.3
  path_provider: ^2.1.3
  vibration: ^1.8.4
  shimmer: ^3.0.0
  flutter_widget_from_html_core: ^0.15.2
  http: ^1.2.1
  image_picker: ^1.1.0
  intl: any
  phone_numbers_parser: ^8.2.1
  country_code_picker: ^3.0.0
  cached_network_image: ^3.3.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
    - assets/language/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
